# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: petshop.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'petshop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpetshop.proto\"w\n\x07\x43liente\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03rua\x18\x03 \x01(\t\x12\x0e\n\x06\x62\x61irro\x18\x04 \x01(\t\x12\x13\n\x0bnumero_casa\x18\x05 \x01(\t\x12\x10\n\x08telefone\x18\x06 \x01(\t\x12\x0b\n\x03\x63pf\x18\x07 \x01(\t\"V\n\x03Pet\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0e\n\x06\x61nimal\x18\x02 \x01(\t\x12\x16\n\x04\x64ono\x18\x03 \x01(\x0b\x32\x08.Cliente\x12\x0c\n\x04raca\x18\x04 \x01(\t\x12\x0b\n\x03rga\x18\x05 \x01(\t\":\n\x07Servico\x12\x10\n\x08pet_nome\x18\x01 \x01(\t\x12\x0f\n\x07servico\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\")\n\x0b\x43lienteList\x12\x1a\n\x08\x63lientes\x18\x01 \x03(\x0b\x32\x08.Cliente\"\x1d\n\x07PetList\x12\x12\n\x04pets\x18\x01 \x03(\x0b\x32\x04.Pet\")\n\x0bServicoList\x12\x1a\n\x08servicos\x18\x01 \x03(\x0b\x32\x08.Servico\"\x18\n\x05Grupo\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf0\x01\n\x07PetShop\x12!\n\nAddCliente\x12\x08.Cliente\x1a\t.Response\x12\x19\n\x06\x41\x64\x64Pet\x12\x04.Pet\x1a\t.Response\x12!\n\nAddServico\x12\x08.Servico\x1a\t.Response\x12$\n\x0cListClientes\x12\x06.Empty\x1a\x0c.ClienteList\x12\x1c\n\x08ListPets\x12\x06.Empty\x1a\x08.PetList\x12$\n\x0cListServicos\x12\x06.Empty\x1a\x0c.ServicoList\x12\x1a\n\x08GetGrupo\x12\x06.Empty\x1a\x06.Grupob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'petshop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTE']._serialized_start=17
  _globals['_CLIENTE']._serialized_end=136
  _globals['_PET']._serialized_start=138
  _globals['_PET']._serialized_end=224
  _globals['_SERVICO']._serialized_start=226
  _globals['_SERVICO']._serialized_end=284
  _globals['_RESPONSE']._serialized_start=286
  _globals['_RESPONSE']._serialized_end=313
  _globals['_EMPTY']._serialized_start=315
  _globals['_EMPTY']._serialized_end=322
  _globals['_CLIENTELIST']._serialized_start=324
  _globals['_CLIENTELIST']._serialized_end=365
  _globals['_PETLIST']._serialized_start=367
  _globals['_PETLIST']._serialized_end=396
  _globals['_SERVICOLIST']._serialized_start=398
  _globals['_SERVICOLIST']._serialized_end=439
  _globals['_GRUPO']._serialized_start=441
  _globals['_GRUPO']._serialized_end=465
  _globals['_PETSHOP']._serialized_start=468
  _globals['_PETSHOP']._serialized_end=708
# @@protoc_insertion_point(module_scope)
